# Generated by Django 5.2 on 2026-07-29 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("slim", "Slim"),
                            ("athletic", "Athletic"),
                            ("average", "Average"),
                            ("plus", "Plus"),
                        ],
                        default="average",
                        max_length=15,
                    ),
                ),
                (
                    "skin_tone",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium-light", "Medium Light"),
                            ("medium", "Medium"),
                            ("medium-dark", "Medium Dark"),
                            ("dark", "Dark"),
                        ],
                        default="medium",
                        max_length=15,
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=170.0,
                        help_text="Height in cm",
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=70.0,
                        help_text="Weight in kg",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
