# Generated by Django 5.2 on 2026-07-29 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatarprofile",
            name="age",
            field=models.PositiveIntegerField(
                default=25,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddField(
            model_name="avatarprofile",
            name="chest",
            field=models.FloatField(
                default=90.0, help_text="Chest circumference in cm"
            ),
        ),
        migrations.AddField(
            model_name="avatarprofile",
            name="hips",
            field=models.FloatField(
                blank=True,
                default=95.0,
                help_text="Hips circumference in cm",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="avatarprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="avatarprofile",
            name="shoulder_width",
            field=models.FloatField(
                default=45.0, help_text="Shoulder to shoulder width in cm"
            ),
        ),
        migrations.AddField(
            model_name="avatarprofile",
            name="waist",
            field=models.FloatField(
                default=80.0, help_text="Waist circumference in cm"
            ),
        ),
        migrations.AlterField(
            model_name="avatarprofile",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("slim", "Slim"),
                    ("athletic", "Athletic"),
                    ("average", "Average"),
                    ("plus", "Plus"),
                    ("inverted_triangle", "Inverted Triangle"),
                    ("pear", "Pear"),
                    ("rectangle", "Rectangle"),
                ],
                default="average",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="avatarprofile",
            name="height",
            field=models.FloatField(
                default=170.0,
                help_text="Height in cm",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="avatarprofile",
            name="skin_tone",
            field=models.CharField(
                choices=[
                    ("fair", "Fair"),
                    ("light", "Light"),
                    ("medium", "Medium"),
                    ("tan", "Tan"),
                    ("rich", "Rich"),
                    ("deep", "Deep"),
                ],
                default="medium",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="avatarprofile",
            name="weight",
            field=models.FloatField(
                default=70.0,
                help_text="Weight in kg",
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
