# Generated by Django 5.2 on 2026-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0002_avatarprofile_age_avatarprofile_chest_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avatarprofile",
            options={
                "verbose_name": "Avatar Profile",
                "verbose_name_plural": "Avatar Profiles",
            },
        ),
        migrations.AlterField(
            model_name="avatarprofile",
            name="hips",
            field=models.FloatField(default=95.0, help_text="Hips circumference in cm"),
        ),
        migrations.AlterField(
            model_name="avatarprofile",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="avatarprofile",
            name="shoulder_width",
            field=models.FloatField(
                default=45.0, help_text="Shoulder-to-shoulder width in cm"
            ),
        ),
    ]
