# Generated by Django 5.2 on 2026-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "avatars",
            "0003_alter_avatarprofile_options_alter_avatarprofile_hips_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatarprofile",
            name="skin_tone",
            field=models.CharField(
                choices=[
                    ("ivory", "Ivory"),
                    ("fair", "Fair"),
                    ("light", "Light"),
                    ("honey", "Honey"),
                    ("medium", "Medium"),
                    ("caramel", "Caramel"),
                    ("tan", "Tan"),
                    ("chestnut", "Chestnut"),
                    ("rich", "Rich"),
                    ("espresso", "Espresso"),
                    ("deep", "Deep"),
                    ("ebony", "Ebony"),
                ],
                default="medium",
                max_length=15,
            ),
        ),
    ]
