# Generated by Django 5.2 on 2026-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="avatar_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Frozen avatar measurements captured at checkout. Used by tailors for custom fit.",
                null=True,
            ),
        ),
    ]
