# Generated by Django 5.2 on 2026-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_avatar_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
