# Generated by Django 5.2 on 2026-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_verified_otpcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slim", "Slim"),
                    ("athletic", "Athletic"),
                    ("average", "Average"),
                    ("curvy", "Curvy"),
                    ("plus_size", "Plus Size"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skin_tone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fair", "Fair"),
                    ("light", "Light"),
                    ("medium", "Medium"),
                    ("tan", "Tan"),
                    ("deep", "Deep"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
