# Generated by Django 5.2 on 2026-07-21 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_avatar_image_alter_profile_body_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(default="Home", max_length=50)),
                ("full_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=30)),
                (
                    "region",
                    models.CharField(blank=True, default="Addis Ababa", max_length=100),
                ),
                ("city", models.CharField(max_length=100)),
                ("sub_city", models.CharField(blank=True, max_length=100)),
                ("woreda", models.CharField(blank=True, max_length=100)),
                ("house_no", models.CharField(blank=True, max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
