# Generated by Django 5.2 on 2026-10-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_securityauditlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="body_type",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skin_tone",
        ),
    ]
