# Generated by Django 5.2 on 2026-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("chapa", "Chapa")], default="chapa", max_length=20
            ),
        ),
    ]
