# Generated by Django 5.2 on 2026-07-03 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Variant label (e.g. White - M - Cotton)",
                        max_length=150,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit (unique identifier)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Color of this variant", max_length=50
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Size (S, M, L, XL or numeric)",
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of this variant",
                        max_digits=10,
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Available quantity in inventory"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="If false, variant is hidden"
                    ),
                ),
                (
                    "measurements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Body/garment measurements for 3D try-on",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Parent product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["price"],
            },
        ),
    ]
