# Generated by Django 5.2 on 2026-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["display_order", "-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Manual curation order within a category. Lower shows first.",
            ),
        ),
    ]
