# Generated by Django 5.2 on 2026-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="reserved_stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Reserved during checkout but not yet paid."
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Total physical inventory."
            ),
        ),
    ]
