# Generated by Django 5.2 on 2026-07-03 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productvariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        help_text="Type of media",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Image or video file", upload_to="products/media/"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Accessibility / SEO text", max_length=255
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Main image shown on product card"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls ordering in gallery / animation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Variant this media belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Media",
                "verbose_name_plural": "Product Media",
                "ordering": ["display_order"],
            },
        ),
    ]
