# Generated by Django 5.2 on 2026-10-07 18:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productbookmark"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="products_pr_is_acti_ca4d9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="products_pr_created_52f0d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["display_order"], name="products_pr_display_288ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "name", "description", "brand", config="english"
                ),
                name="product_search_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["price"], name="products_pr_price_a59bc5_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_active"], name="products_pr_is_acti_9d6315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["color"], name="products_pr_color_03331d_idx"),
        ),
    ]
