# Generated by Django 5.2 on 2026-10-08 21:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_products_pr_is_acti_ca4d9a_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Category banner.",
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    resource_type="auto"
                ),
                upload_to="tilet3d/categories/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category thumbnail.",
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    resource_type="auto"
                ),
                upload_to="tilet3d/categories/images/",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    resource_type="auto"
                ),
                upload_to="tilet3d/products/media/",
            ),
        ),
    ]
